from arena_proxy_bot.arena.modes import ArenaModelOption


FALLBACK_MODEL_CATALOG: dict[str, tuple[ArenaModelOption, ...]] = {
    "text": (
        ArenaModelOption(
            "Max",
            "Intelligently routes you to the most capable model for your specific prompt with latency in mind. Learn more",
        ),
        ArenaModelOption("gemini-3-flash", ""),
        ArenaModelOption("gpt-5.2-chat-latest", ""),
        ArenaModelOption("glm-5.1", ""),
        ArenaModelOption("qwen3.5-397b-a17b", ""),
        ArenaModelOption("gemini-3.1-pro-preview", ""),
        ArenaModelOption("grok-4.20-beta-0309-reasoning", ""),
        ArenaModelOption("gpt-5.5-instant", ""),
        ArenaModelOption("claude-sonnet-4-6", ""),
        ArenaModelOption("grok-4.20-multi-agent-beta-0309", ""),
        ArenaModelOption("qwen3.5-max-preview", ""),
        ArenaModelOption("qwen3.7-plus", ""),
        ArenaModelOption("glm-5", ""),
        ArenaModelOption("claude-sonnet-4-5-20250929-thinking-32k", ""),
        ArenaModelOption("claude-sonnet-4-5-20250929", ""),
        ArenaModelOption("gpt-5.1-high", ""),
        ArenaModelOption("gpt-5.4-mini-high", ""),
        ArenaModelOption("gpt-5.3-chat-latest", ""),
        ArenaModelOption("mimo-v2-pro", ""),
        ArenaModelOption("minimax-m3", ""),
        ArenaModelOption("gemini-2.5-pro", ""),
        ArenaModelOption("glm-4.7", ""),
        ArenaModelOption("gpt-5.1", ""),
        ArenaModelOption("gpt-5.2-high", ""),
        ArenaModelOption("gpt-5.2", ""),
        ArenaModelOption("qwen3-max-preview", ""),
        ArenaModelOption("gpt-5-high", ""),
        ArenaModelOption("kimi-k2.5-instant", ""),
        ArenaModelOption("gemini-3.1-flash-lite-preview", ""),
        ArenaModelOption("mimo-v2-omni", ""),
        ArenaModelOption("o3-2025-04-16", ""),
        ArenaModelOption("kimi-k2-thinking-turbo", ""),
        ArenaModelOption("gpt-5-chat", ""),
        ArenaModelOption("qwen3-max-2025-09-23", ""),
        ArenaModelOption("qwen3-235b-a22b-instruct-2507", ""),
        ArenaModelOption("kimi-k2-0905-preview", ""),
        ArenaModelOption("kimi-k2-0711-preview", ""),
        ArenaModelOption("qwen3.5-122b-a10b", ""),
        ArenaModelOption("minimax-m2.7", ""),
        ArenaModelOption("mistral-large-3", ""),
        ArenaModelOption("qwen3-vl-235b-a22b-instruct", ""),
        ArenaModelOption("gpt-4.1-2025-04-14", ""),
        ArenaModelOption("claude-haiku-4-5-20251001", ""),
        ArenaModelOption("gemini-2.5-flash", ""),
        ArenaModelOption("mistral-medium-2508", ""),
        ArenaModelOption("qwen3.5-27b", ""),
        ArenaModelOption("gpt-5.4-nano-high", ""),
        ArenaModelOption("qwen3-235b-a22b-no-thinking", ""),
        ArenaModelOption("qwen3-next-80b-a3b-instruct", ""),
        ArenaModelOption("longcat-flash-chat", ""),
        ArenaModelOption("qwen3-235b-a22b-thinking-2507", ""),
        ArenaModelOption("claude-sonnet-4-20250514-thinking-32k", ""),
        ArenaModelOption("qwen3.5-flash", ""),
        ArenaModelOption("qwen3.5-35b-a3b", ""),
        ArenaModelOption("qwen3-vl-235b-a22b-thinking", ""),
        ArenaModelOption("hunyuan-vision-1.5-thinking", ""),
        ArenaModelOption("step-3.5-flash", ""),
        ArenaModelOption("mimo-v2-flash (thinking)", ""),
        ArenaModelOption("mimo-v2-flash", ""),
        ArenaModelOption("minimax-m2.5", ""),
        ArenaModelOption("gpt-5-mini-high", ""),
        ArenaModelOption("o4-mini-2025-04-16", ""),
        ArenaModelOption("claude-sonnet-4-20250514", ""),
        ArenaModelOption("qwen3-coder-480b-a35b-instruct", ""),
        ArenaModelOption("mistral-medium-2505", ""),
        ArenaModelOption("minimax-m2.1-preview", ""),
        ArenaModelOption("qwen3-30b-a3b-instruct-2507", ""),
        ArenaModelOption("gpt-4.1-mini-2025-04-14", ""),
        ArenaModelOption("trinity-large-preview", ""),
        ArenaModelOption("qwen3-235b-a22b", ""),
        ArenaModelOption("qwen3-next-80b-a3b-thinking", ""),
        ArenaModelOption("trinity-large-thinking", ""),
        ArenaModelOption("gemma-3-27b-it", ""),
        ArenaModelOption("minimax-m1", ""),
        ArenaModelOption("gemini-2.0-flash-001", ""),
        ArenaModelOption("mistral-small-2506", ""),
        ArenaModelOption("intellect-3", ""),
        ArenaModelOption("gpt-oss-120b", ""),
        ArenaModelOption("o3-mini", ""),
        ArenaModelOption("mercury-2", ""),
        ArenaModelOption("ling-flash-2.0", ""),
        ArenaModelOption("minimax-m2", ""),
        ArenaModelOption("gpt-5-nano-high", ""),
        ArenaModelOption("nova-2-lite", ""),
        ArenaModelOption("qwq-32b", ""),
        ArenaModelOption("olmo-3.1-32b-instruct", ""),
        ArenaModelOption("qwen3-30b-a3b", ""),
        ArenaModelOption("ring-flash-2.0", ""),
        ArenaModelOption("gemma-3n-e4b-it", ""),
        ArenaModelOption("gpt-oss-20b", ""),
        ArenaModelOption("nvidia-nemotron-3-nano-30b-a3b-bf16", ""),
        ArenaModelOption("granite-4.1-8b", ""),
        ArenaModelOption("mercury", ""),
        ArenaModelOption("mistral-small-3.1-24b-instruct-2503", ""),
        ArenaModelOption("ibm-granite-h-small", ""),
        ArenaModelOption("olmo-3.1-32b-think", ""),
        ArenaModelOption("ring-2.5-1t", ""),
        ArenaModelOption("ling-2.5-1t", ""),
        ArenaModelOption("dola-seed-2.0-preview-vision", ""),
        ArenaModelOption("nvidia-nemotron-3-super-120b-a12b", ""),
        ArenaModelOption("dola-seed-2.0-preview-text", ""),
        ArenaModelOption("qwen3.6-27b", ""),
        ArenaModelOption("gemma-4-31b", ""),
        ArenaModelOption("nvidia-nemotron-3-ultra-550b-a55b-nvfp4", ""),
        ArenaModelOption("gemma-4-26b-a4b", ""),
        ArenaModelOption("gemini-3.5-flash", ""),
        ArenaModelOption("mimo-v2.5-pro", ""),
        ArenaModelOption("qwen3.7-plus-preview", ""),
        ArenaModelOption("qwen3.6-max-preview", ""),
        ArenaModelOption("mistral-small-2603", ""),
        ArenaModelOption("ernie-5.0-preview-1220", ""),
        ArenaModelOption("kimi-k2.5-thinking", ""),
        ArenaModelOption("qwen3.7-max", ""),
        ArenaModelOption("gpt-5-high-new-system-prompt", ""),
        ArenaModelOption("deepseek-v4-pro-thinking", ""),
        ArenaModelOption("qwen3-vl-8b-thinking", ""),
        ArenaModelOption("qwen3.6-plus", ""),
        ArenaModelOption("mistral-medium-3.5", ""),
        ArenaModelOption("gemini-3-flash (thinking-minimal)", ""),
        ArenaModelOption("qwen-vl-max-2025-08-13", ""),
        ArenaModelOption("qwen3-omni-flash", ""),
        ArenaModelOption("qwen3-vl-8b-instruct", ""),
        ArenaModelOption("grok-4.3", ""),
        ArenaModelOption("deepseek-v4-flash", ""),
        ArenaModelOption("mimo-v2.5", ""),
        ArenaModelOption("amazon.nova-pro-v1:0", ""),
        ArenaModelOption("deepseek-v4-flash-thinking", ""),
        ArenaModelOption("minimax-m2-preview", ""),
        ArenaModelOption("glm-5.2 (max)", ""),
        ArenaModelOption("qwen3.7-max-preview", ""),
        ArenaModelOption("kimi-k2.6", ""),
        ArenaModelOption("deepseek-v4-pro", ""),
        ArenaModelOption("qwen3-max-thinking", ""),
        ArenaModelOption("qwen3-max-2025-09-26", ""),
        ArenaModelOption("glm-5v-turbo", ""),
    ),
    "search": (
        ArenaModelOption(
            "Max",
            "Intelligently routes you to the most capable model for your specific prompt with latency in mind. Learn more",
        ),
        ArenaModelOption("claude-sonnet-4-6-search", ""),
        ArenaModelOption("grok-4.20-multi-agent-beta-0309", ""),
        ArenaModelOption("gpt-5.2-search", ""),
        ArenaModelOption("gemini-3-flash-grounding", ""),
        ArenaModelOption("gpt-5.1-search", ""),
        ArenaModelOption("gpt-5.2-search-non-reasoning", ""),
        ArenaModelOption("grok-4-1-fast-search", ""),
        ArenaModelOption("claude-sonnet-4-5-search", ""),
        ArenaModelOption("o3-search", ""),
        ArenaModelOption("gemini-2.5-pro-grounding", ""),
        ArenaModelOption("grok-4-search", ""),
        ArenaModelOption("ppl-sonar-reasoning-pro-high", ""),
        ArenaModelOption("gpt-5-search", ""),
        ArenaModelOption("gpt-5.1-search-sp", ""),
        ArenaModelOption("grok-4.3", ""),
    ),
    "image": (
        ArenaModelOption(
            "Max",
            "Intelligently routes you to the most capable model for your specific prompt with latency in mind. Learn more",
        ),
        ArenaModelOption("flux-2-pro", ""),
        ArenaModelOption("reve-v1.5", ""),
        ArenaModelOption("flux-2-dev", ""),
        ArenaModelOption("seedream-4.5", ""),
        ArenaModelOption("seedream-5.0-lite", ""),
        ArenaModelOption("imagen-4.0-generate-001", ""),
        ArenaModelOption("qwen-image-2512", ""),
        ArenaModelOption("hidream-o1-image", ""),
        ArenaModelOption("krea-2-medium", ""),
        ArenaModelOption("wan2.5-t2i-preview", ""),
        ArenaModelOption("gpt-image-1", ""),
        ArenaModelOption("recraft-v4", ""),
        ArenaModelOption("wan2.7-image-pro", ""),
        ArenaModelOption("krea-2-large", ""),
        ArenaModelOption("wan2.7-image", ""),
        ArenaModelOption("seedream-3", ""),
        ArenaModelOption("cosmos3-super", ""),
        ArenaModelOption("flux-1-kontext-pro", ""),
        ArenaModelOption("imagen-3.0-generate-002", ""),
        ArenaModelOption("cosmos3-super-agentic", ""),
        ArenaModelOption("ideogram-v3-quality", ""),
        ArenaModelOption("photon", ""),
        ArenaModelOption("recraft-v3", ""),
        ArenaModelOption("lucid-origin", ""),
        ArenaModelOption("flux-1-kontext-dev", ""),
        ArenaModelOption("qwen-image-2.0", ""),
        ArenaModelOption("qwen-image-2.0-pro", ""),
        ArenaModelOption("uni-1.1-max", ""),
        ArenaModelOption("uni-1.1", ""),
        ArenaModelOption("hunyuan-image-3.0-instruct", ""),
        ArenaModelOption("reve-2.0 (text-to-image)", ""),
        ArenaModelOption("seededit-3.0", ""),
        ArenaModelOption("grok-imagine-image-quality (20260519)", ""),
        ArenaModelOption("mai-image-2.5 (text-to-image)", ""),
        ArenaModelOption("mai-image-2.5 (image-edit)", ""),
        ArenaModelOption("reve-2.0 (image-edit)", ""),
        ArenaModelOption("gemini-2.5-flash-image-preview (nano-banana)", ""),
        ArenaModelOption("grok-imagine-image-quality", ""),
        ArenaModelOption("hunyuan-image-2.1", ""),
        ArenaModelOption("grok-imagine-image", ""),
        ArenaModelOption("qwen-image-edit", ""),
        ArenaModelOption("wan2.5-i2i-preview", ""),
        ArenaModelOption("imagen-4.0-ultra-generate-001", ""),
        ArenaModelOption("wan2.6-t2i", ""),
        ArenaModelOption("imagen-4.0-fast-generate-001", ""),
        ArenaModelOption("qwen-image-edit-2511", ""),
        ArenaModelOption("wan2.6-image", ""),
    ),
    "vip": (
        ArenaModelOption(
            "Max",
            "Intelligently routes you to the most capable model for your specific prompt with latency in mind. Learn more",
        ),
    ),
}
